### ISSUE TITLE
MIUI用无线启动shizuku之后，显示adb功能受限

### ISSUE THREAD

**Issue by winteboo** [android-in-china/Compatibility#26]
* 设备厂商：小米10
* 设备型号：miui12.5.10
* Android 版本：11

找了半天网上半点信息没有。。。但是在B站几个视频下面看到有几个人和我一样的问题，没法解决，我查了一下这里的issues，可能需要去asop给shizuku权限，可是根本找不到怎么进asop的办法、。。求大佬支支招

**Comment by oasisfeng** [comment]
此 issue tracker 仅供分享与开发相关的兼容性问题，MIUI 此机制属于用户最终层面的功能设计。
