### ISSUE TITLE
Chrome时常假死MIUI9&10

### ISSUE THREAD

**Issue by ShermanQ** [android-in-china/Compatibility#5]
Chrome经常性在打开一个网页的时候假死，具体表现为触摸全部失效，必须要关掉Chrome，重新打开才可以使用。
MIUI9及10时常复现，频率大概每50次使用出现一次，大约一天一次。
机型小米6 [6GB/128G]

**Comment by ryuunoakaihitomi** [comment]
@ShermanQ 这里是用来反馈**Android API**的兼容性问题的，不是针对于某一个具体应用或者使用上的bug的反馈处。请到[MIUI论坛](http://www.miui.com/forum.php)反馈此问题。
