### ISSUE TITLE
谷歌“保护机制”

### ISSUE THREAD

**Issue by wangjian1154** [android-in-china/Compatibility#7]
* 设备厂商：带有保护机制的高版本安卓手机
* 设备型号：华为荣耀8,、华为p10等以上版本手机
* 设备 ROM：EMUI，MIUI，锤子，原生安卓等
* Android 版本：Android 7.0以上
* 在“”设置”——“安全”，中有个谷歌安全机制，会将自己的app或者大厂app检测出为有害应用，如图
【1】https://qimg.ithome.com/image/2018/02/10/6365390099083599746847195.png
【2】https://ws4.sinaimg.cn/large/006tKfTcly1fmyh2ly7m4j30u01fqteq.jpg
【3】https://attach.bbs.miui.com/forum/201706/18/094644hd082ky08zdndknj.png.thumb.jpg

**Comment by oasisfeng** [comment]
抱歉，这里仅限反馈与 Android SDK 之间的兼容性问题。
