### ISSUE TITLE
miui ble蓝牙搜索设备问题

### ISSUE THREAD

**Issue by CaiJingLong** [android-in-china/Compatibility#8]
* 设备厂商：小米
* 设备型号：MI 8/MI 6
* 设备 ROM：MIUI 9.5 稳定版
* Android 版本：Android 8.1
* 涉及的 Android API：蓝牙BLE扫描相关
* 预期表现：能够搜索到所有的BLE蓝牙设备
* 实际表现：仅能搜索到部分蓝牙设备
* 相关 logcat 日志：无
* 补充说明：用其他的设备,如魅族/华为/小米note2等可以搜索到,iphone/ipad/mac 的蓝牙调试工具也可以搜索到

**Comment by oasisfeng** [comment]
这其实属于设备间的兼容性问题（涉及的是硬件底层的兼容性），不在本项目关注的 Android API 兼容性范畴内。
