### ISSUE TITLE
Android 8.1 屏幕旋转混乱

### ISSUE THREAD

**Issue by chengfan2017** [android-in-china/Compatibility#9]
* 设备厂商：Pixel XL 、Nexus 5X 、诺基亚 ....
* 设备型号：（可列举多个型号，不必覆盖全部有此问题的型号）
* 设备 ROM：（请勿在此反馈社区 ROM 的相关问题）
* Android 版本：8.1.0
* 涉及的 Android API：（请尽可能全面的列举或描述涉及到的 API）27
* 预期表现：固定屏幕方向
* 实际表现：屏幕方向会暂时混乱再恢复正常（不是必然）
* 相关 logcat 日志：
* 补充说明：这个bug只在8.1的手机上会出现，google Issue Tracker 已经有人提交了https://issuetracker.google.com/issues/69168442#comment51
google已经把这个问题收录，确定在下一个版本修复。但现在还没有具体兼容解决方案，希望国内大神能研究一下，谢谢

**Comment by oasisfeng** [comment]
此处仅提供与 Android API 的兼容性问题反馈。

**Comment by joimxjtuse** [comment]
在使用支持库（v 7-25.0.0）所提供的夜间模式功能的时候，android 8.0， 8.1 ， 我遇到了个奇怪的问题， 当切换模式后， 横竖屏切换（比如视频的全屏播放功能），日夜间素材会混乱掉，   我尝试升级 支持库版本到最新的也依然有这个问题， 目前我用的三星、vivo 等手机都遇到了， 不知道有人遇到过没。

issue tracker上有人提过，但好像是23左右的支持库版本后来修复了， 现在只在8.0以上的手机发现过。

**Comment by oasisfeng** [comment]
@joimxjtuse 听起来更像是 support library 或者 AOSP 本身的问题。本项目目前仅接收机型相关的 Android API 兼容性问题反馈。

**Comment by joimxjtuse** [comment]
@oasisfeng ,这样， get it.

**Comment by mosentest** [comment]
666
